"use client";

import { useState, useEffect } from "react";
import Button from "@/components/ui/Button";
import Badge from "@/components/ui/Badge";
import Spinner from "@/components/ui/Spinner";
import { getSettingsHeaders } from "@/lib/settings";

interface ReportPreviewProps {
  reportUrl?: string;
  analysisId?: string;
}

export default function ReportPreview({ reportUrl: initialReportUrl, analysisId }: ReportPreviewProps) {
  const [generating, setGenerating] = useState(false);
  const [reportUrl, setReportUrl] = useState<string | null>(initialReportUrl || null);
  const [checking, setChecking] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function checkExistingReport() {
      if (!analysisId) {
        setChecking(false);
        return;
      }
      try {
        const res = await fetch(`/api/report?analysisId=${analysisId}`, {
          headers: getSettingsHeaders(),
        });
        if (res.ok) {
          const data = await res.json();
          if (data.found && data.reportUrl) {
            setReportUrl(data.reportUrl);
          }
        }
      } catch (err) {
        console.warn("Error checking existing report:", err);
      } finally {
        setChecking(false);
      }
    }
    checkExistingReport();
  }, [analysisId]);

  async function handleGenerate() {
    if (!analysisId) return;
    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...getSettingsHeaders(),
        },
        body: JSON.stringify({ analysisId }),
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.error || "Failed to compile report PDF.");
      }

      const data = await res.json();
      if (data.success && data.reportUrl) {
        setReportUrl(data.reportUrl);
      } else {
        throw new Error("Did not receive a valid report URL.");
      }
    } catch (err: any) {
      console.error("PDF generation error:", err);
      setError(err.message || "An unexpected error occurred during PDF generation.");
    } finally {
      setGenerating(false);
    }
  }

  if (checking) {
    return (
      <div className="flex flex-col items-center justify-center p-8 border border-border rounded-lg bg-bg-surface/30">
        <Spinner size="md" />
        <p className="text-xs text-text-tertiary mt-2">Checking report archives...</p>
      </div>
    );
  }

  return (
    <div className="space-y-5 animate-slide-up">
      {/* Report meta card */}
      <div className="card p-6">
        <div className="flex items-start justify-between">
          <div>
            <p className="t-subheading mb-1.5">Document</p>
            <h2 className="text-base font-semibold text-text-primary tracking-tight">
              UAE VAT Compliance Audit Report
            </h2>
            <p className="text-xs text-text-tertiary mt-1">
              Reference: {analysisId ? `REF-${analysisId.slice(0, 8).toUpperCase()}` : "—"} · Generated by TaxPilot
            </p>
          </div>
          <Badge label={reportUrl ? "Finalized" : "Draft"} variant={reportUrl ? "success" : "outline"} />
        </div>

        <hr className="divider my-5" />

        {/* Report sections overview */}
        <div className="grid grid-cols-3 gap-4">
          {[
            { section: "Executive Summary", pages: "1", status: reportUrl ? "Ready" : "Draft" },
            { section: "Compliance Score",  pages: "1",   status: reportUrl ? "Ready" : "Draft" },
            { section: "Findings & Risks",  pages: "1–2", status: reportUrl ? "Ready" : "Draft" },
            { section: "Recommendations",   pages: "2", status: reportUrl ? "Ready" : "Draft" },
            { section: "Supporting Data",   pages: "2–4", status: reportUrl ? "Ready" : "Draft" },
            { section: "FTA Rules Mapping",  pages: "3",   status: reportUrl ? "Ready" : "Draft"  },
          ].map(({ section, pages, status }) => (
            <div
              key={section}
              className="bg-bg-base border border-border-strong rounded-md px-4 py-3"
            >
              <p className="text-xs font-medium text-text-primary truncate">{section}</p>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-2xs text-text-tertiary tabular-nums">p. {pages}</span>
                <span className="text-2xs text-text-disabled">·</span>
                <span className={`text-2xs ${status === "Ready" ? "text-success font-medium" : "text-text-tertiary"}`}>
                  {status}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {error && (
        <div className="bg-critical/10 border border-critical/20 rounded-lg p-4 text-critical text-xs flex gap-2">
          <span>⚠️</span>
          <div>
            <p className="font-semibold mb-0.5">Failed to compile PDF</p>
            <p>{error}</p>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center gap-3">
        <Button
          variant="primary"
          size="md"
          loading={generating}
          onClick={handleGenerate}
          id="generate-report-btn"
        >
          {generating ? "Compiling PDF…" : reportUrl ? "Re-generate PDF report" : "Generate PDF report"}
        </Button>

        {reportUrl && (
          <a href={reportUrl} target="_blank" rel="noreferrer" download>
            <Button variant="secondary" size="md" type="button">
              Download PDF
            </Button>
          </a>
        )}

        <Button variant="ghost" size="md" onClick={() => window.location.href = `/dashboard/${analysisId}`}>
          Back to Dashboard
        </Button>
      </div>

      {!reportUrl && !generating && (
        <p className="text-xs text-text-tertiary">
          The report will be compiled using official FTA layout templates. Generation takes 2–4 seconds.
        </p>
      )}

      {reportUrl && (
        <div className="border border-border/80 rounded-lg overflow-hidden bg-bg-surface/50 h-[650px] w-full animate-fade-in mt-6 shadow-inner">
          <iframe
            src={reportUrl}
            title="UAE VAT Compliance Audit PDF Preview"
            className="w-full h-full border-0"
          />
        </div>
      )}
    </div>
  );
}